"""create initial database schema 

Revision ID: a24be4151b86
Revises: d6c6ccf6e82e
Create Date: 2026-08-05 13:57:43.580020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24be4151b86'
down_revision: Union[str, Sequence[str], None] = 'd6c6ccf6e82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('allergy_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('next_appointment', sa.Date(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_table('labs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('adherence_notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('glucose', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patients', sa.Column('patient_code', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('patients', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('patients', sa.Column('sex', sa.String(length=10), nullable=False))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('assigned_nurse', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('assigned_doctor', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('care_program', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_patients_codice_fiscale'), table_name='patients')
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.drop_column('patients', 'codice_fiscale')
    op.drop_column('patients', 'cognome')
    op.drop_column('patients', 'nome')
    op.drop_column('patients', 'data_nascita')
    op.drop_column('patients', 'validated')
    op.drop_column('patients', 'sesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('sesso', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('validated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('data_nascita', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('cognome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('codice_fiscale', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.create_index(op.f('ix_patients_codice_fiscale'), 'patients', ['codice_fiscale'], unique=True)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'enrollment_date')
    op.drop_column('patients', 'care_program')
    op.drop_column('patients', 'assigned_doctor')
    op.drop_column('patients', 'assigned_nurse')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    op.drop_column('patients', 'patient_code')
    op.drop_table('vitals')
    op.drop_table('visits')
    op.drop_table('medications')
    op.drop_table('labs')
    op.drop_table('insurance')
    op.drop_table('conditions')
    op.drop_table('care_plans')
    op.drop_table('allergies')
    op.drop_table('alerts')
    # ### end Alembic commands ###
